### ISSUE TITLE
Visualization method (point cloud with shadow)

### ISSUE THREAD

**Issue by JLee2022** [ltwu6/cross-pcc#2]
Dear author, I am eager to know which programming library you used to visualize the results in your paper. I think they are particularly beautiful, especially the shadows below the point clouds, and I hope to refer to them in my writing

**Comment by ltwu6** [comment]
Hi, we used KeyShot to visualize the point clouds. You can adjust the shadows and colors of the points according to your needs by using KeyShot.
________________________________
发件人: JLee2022 ***@***.***>
发送时间: 2024年3月6日 19:05
收件人: ltwu6/cross-pcc ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Ext] [ltwu6/cross-pcc] Visualization method (point cloud with shadow) (Issue #2)

CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.


Dear author, I am eager to know which programming library you used to visualize the results in your paper. I think they are particularly beautiful, especially the shadows below the point clouds, and I hope to refer to them in my writing

―
